### ISSUE TITLE
footer is not at bottom

### ISSUE THREAD

**Issue by QimatLuo** [Jimmyluluu/PersonalBlog#3]
If you add more articles to let website can scroll.
Then you can see the footer is not always at the bottom.

![image](https://user-images.githubusercontent.com/9548054/224472603-4b2e3685-6911-46dc-9707-8ce8bfaac84e.png)

**Comment by Jimmyluluu** [comment]
Deal

**Comment by QimatLuo** [comment]
Actually, if you want the footer "always" at the bottom, then it's not fixed.

**Comment by QimatLuo** [comment]
Remember to `npm run format`.

**Comment by QimatLuo** [comment]
by the way, if you use pull request, then I'll be easier to comment on the code change.

**Comment by Jimmyluluu** [comment]
OKKK

**Comment by Jimmyluluu** [comment]
I think this footer is good at me
